Q1: Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [8]:
import numpy as np
array = np.random.randint(1, 101, size=(3, 3))

print('Before \n', array)
transposed_array = array.T
print('After \n', transposed_array)

Before 
 [[55 76 44]
 [16 95 32]
 [57 34 44]]
After 
 [[55 16 57]
 [76 95 34]
 [44 32 44]]


Q2: Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [9]:
import numpy as np
array = np.arange(10)

array_2x5 = array.reshape(2, 5)
print('Before \n', array_2x5)
array_5x2 = array.reshape(5, 2)
print('After \n', array_5x2)

Before 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
After 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Q3:  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [10]:
import numpy as np

arr = np.random.rand(4, 4)
padded_arr = np.pad(arr, ((1, 1), (1, 1)), 'constant', constant_values=0)

print(padded_arr)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.10609298 0.3023463  0.72810409 0.64403174 0.        ]
 [0.         0.11120263 0.02855859 0.74554403 0.92575403 0.        ]
 [0.         0.83015826 0.63522695 0.80965556 0.43820578 0.        ]
 [0.         0.20691142 0.62852945 0.81665929 0.86745175 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Q4: Using NumPy, create an array of integers from 10 to 60 with a step of 5

In [12]:
import numpy as np

arr = np.arange(10, 61, 5)

print(arr)

[10 15 20 25 30 35 40 45 50 55 60]


Q5:  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations 
(uppercase, lowercase, title case, etc.) to each element

In [13]:
import numpy as np

# Create the NumPy array
arr = np.array(['python', 'numpy', 'pandas'])

# Uppercase
print(np.char.upper(arr))

# Lowercase
print(np.char.lower(arr))

# Title case
print(np.char.title(arr))

['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


Q6: Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [16]:
import numpy as np

# Create the NumPy array
arr = np.array(['hello', 'world'])

# Insert space between characters
result = np.char.join(' ', arr)

# Print the result
print(result)

['h e l l o' 'w o r l d']


Q7: Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [17]:
import numpy as np

# Create two 2D arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Element-wise addition
print(a + b)

# Element-wise subtraction
print(a - b)

# Element-wise multiplication
print(a * b)

# Element-wise division
print(a / b)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


Q8: Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [18]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)

# Extract diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

# Print the diagonal elements
print(diagonal_elements)

[1. 1. 1. 1. 1.]


Q9: Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in 
this array.

In [19]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
arr = np.random.randint(0, 1001, 100)

# Function to check if a number is prime
def is_prime(n):
  if n <= 1:
    return False
  if n <= 3:
    return True
  if n % 2 == 0 or n % 3 == 0:
    return False
  i = 5
  while i * i <= n:
    if n % i == 0 or n % (i + 2) == 0:
      return False
    i = i + 6
  return True

# Find and display all prime numbers in the array
primes = []
for num in arr:
  if is_prime(num):
    primes.append(num)

# Print the prime numbers
print(primes)

[109, 431, 151, 887, 457, 173, 827, 173, 5, 5, 307, 379, 569, 359, 443, 523]


Q10: Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly 
averages.

In [22]:
import numpy as np

# Sample daily temperatures for a month (replace with actual data)
daily_temperatures = np.random.randint(60, 90, size=30)

# Calculate weekly averages
weekly_averages = np.mean(daily_temperatures.reshape(-1, 5), axis=0)

# Display weekly averages
print("Weekly Averages:", weekly_averages)


Weekly Averages: [81.16666667 73.66666667 73.5        72.5        76.83333333]
