In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.4


In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [4]:
l = [1,2,3,4,5,6,7]
print(type(l))
arr = np.array(l)
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [8]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
ll = [1,2,3,"A", "Jibrail"]
print(type(ll))
arr_new = np.array(ll)
print(type(arr_new))

<class 'list'>
<class 'numpy.ndarray'>


In [7]:
arr_new

array(['1', '2', '3', 'A', 'Jibrail'], dtype='<U11')

In [10]:
arr1 = np.array([1,2,3,4,5])
arr1.ndim

1

In [11]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2.ndim

2

In [14]:
print('One Di array : ',arr1)
print('Two Di array : ',arr2)


One Di array :  [1 2 3 4 5]
Two Di array :  [[1 2 3]
 [4 5 6]]


In [16]:
arr3 = np.matrix([1,2,3])
print(type(arr3))
print(arr2.ndim)

<class 'numpy.matrix'>
2


In [17]:
arr4 = np.matrix([[1,2,3],[1,2,3],[1,2,3]])
arr4

matrix([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [18]:
arr3D = np.matrix([[[1,2,3],[1,2,3],[1,2,3]]])

ValueError: matrix must be 2-dimensional

In [19]:
arr3D = np.array([[[1,2,3],[1,2,3],[1,2,3]]])

In [20]:
arr3D

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [21]:
arr3D.ndim

3

In [23]:
list = [1,2,3,4]
arr5 = np.asarray(list)
arr5

array([1, 2, 3, 4])

In [25]:
list = [1,2,3,4]
mat = np.matrix(list)
print(type(mat))

<class 'numpy.matrix'>


In [26]:
arr6 = np.asanyarray(mat)
print(type(arr6))

<class 'numpy.matrix'>


In [28]:
list = [1,2,3,4]
arr = np.asanyarray(list)
type(arr)

numpy.ndarray

In [30]:
a = arr
a

array([1, 2, 3, 4])

In [31]:
a[0]=11
a

array([11,  2,  3,  4])

In [32]:
arr

array([11,  2,  3,  4])

In [33]:
aa = arr.copy()

In [34]:
aa

array([11,  2,  3,  4])

In [35]:
aa[0]=123

In [36]:
aa

array([123,   2,   3,   4])

In [37]:
arr

array([11,  2,  3,  4])

In [43]:
arr7 = np.fromfunction(lambda i, j: i==j, (3,3))

In [44]:
arr7.shape

(3, 3)

In [45]:
np.fromfunction(lambda i, j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [50]:
arr8 = np.fromfunction(lambda i, j: i==j, (3,3))

In [52]:
arr8 = np.fromiter(range(1,10),int)

In [53]:
arr8

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr8 = np.fromstring('11 22 33', sep =' ',dtype=int)
arr8

array([11, 22, 33])

In [1]:
import numpy as np

In [4]:
arr = np.zeros(5, dtype=int)
arr

array([0, 0, 0, 0, 0])

In [7]:
arr1 = np.zeros((3,4), dtype=int)
arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [8]:
arr2 = np.ones((3,4),dtype=int)
arr2


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [18]:
arr3D = np.zeros((3,3,4), dtype=int)
arr3D

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [19]:
arr3D.ndim

3

In [22]:
arr3D + 5 *2 -3

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.empty((3,3))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.11260891e-306, 1.11260280e-306, 1.42413555e-306],
       [1.78019082e-306, 4.79243676e-322, 0.00000000e+000]])

In [28]:
import random
random.choice((1,2,3,4))

1

In [30]:
random.randrange(1,10)

6

In [33]:
random.random()

0.9173973705844745

In [34]:
random.uniform(1,20)

13.371644270911544

In [36]:
np.random.random_sample()

0.34036667831008205

In [35]:
np.random.random_sample(5,)

array([0.95889952, 0.54010859, 0.48653307, 0.30423889, 0.12155813])

In [53]:
arr1 = np.random.rand(2,10)
arr1

array([[0.59950047, 0.52876228, 0.89736248, 0.15570698, 0.09297678,
        0.26475717, 0.85318482, 0.28410043, 0.31652693, 0.94180081],
       [0.14514606, 0.10008962, 0.10002883, 0.08730051, 0.12648977,
        0.83999068, 0.32181484, 0.02192746, 0.74694948, 0.70937498]])

In [49]:
arr= np.random.randn(20,3)

In [54]:
arr1.reshape(5,4).base

array([[0.59950047, 0.52876228, 0.89736248, 0.15570698, 0.09297678,
        0.26475717, 0.85318482, 0.28410043, 0.31652693, 0.94180081],
       [0.14514606, 0.10008962, 0.10002883, 0.08730051, 0.12648977,
        0.83999068, 0.32181484, 0.02192746, 0.74694948, 0.70937498]])

In [52]:
arr1.reshape(,-1).base

array([[0.31864445, 0.35635374, 0.59518229, 0.18291719, 0.23256488,
        0.71451219, 0.52926213, 0.37644724, 0.9963683 , 0.92715599],
       [0.25263988, 0.32811346, 0.60636817, 0.74534906, 0.26947613,
        0.20310225, 0.37324371, 0.59367473, 0.10902968, 0.27000721]])

In [58]:
arr1[arr1 > 1]

array([], dtype=float64)

In [65]:
# O to 1 row and 0 to 1 column
arr[0:1,[0,1]]

array([[0.03950069, 0.28995717]])